# Site settings

title: Duygu DaÄŸdelenn
url: "https://dduyg.github.io"
# Edit next line so that baseurl is "" if your repo is <username>.github.io
baseurl: ""

projects-page-label: Insert Data
essays-page-label: Posts
bio-page-label: About
contact-page-label: Contact

theme-home: theme-home-builtin.html
theme-projects: theme-projects-builtin.html
theme-essays: theme-essays-builtin.html
theme-bio: theme-bio-builtin.html
theme-contact: theme-contact.html

projects-url: insert-data
essays-url: posts
bio-url: about
contact-url: contact

# Specify the rouge syntax highlighter theme. Pick one from css/rouge.
rouge-theme: gruvbox

# YOU NORMALLY NEVER CHANGE THE FOLLOWING
markdown: kramdown
include: [_data]

plugins:
  - jekyll-sitemap
